In [1]:
import tensorflow as tf
import numpy as np
import gym

/Users/akashvelu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/akashvelu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/akashvelu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/akashvelu/.local/lib/python3.6/site-packages/tensorflow/python/framework

In [2]:
from env_params import flow_params as flow_params

ModuleNotFoundError: No module named 'env_params'

In [3]:
from flow.utils.registry import make_create_env
from flow.controllers import IDMController, ContinuousRouter
from flow.core.experiment import Experiment
from flow.core.params import SumoParams, EnvParams, \
    InitialConfig, NetParams
from flow.core.params import VehicleParams
from flow.networks.ring import RingNetwork, ADDITIONAL_NET_PARAMS
import numpy as np
from flow.core.experiment import Experiment
from flow.core.params import InFlows
from flow.core.params import SumoLaneChangeParams
from flow.core.params import SumoCarFollowingParams
from flow.core.params import VehicleParams
from flow.controllers import ContinuousRouter
from flow.benchmarks.bottleneck0 import flow_params
from flow.benchmarks.bottleneck0 import SCALING

/Users/akashvelu/Documents/Research/Research_MobileSensing/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.
  PendingDeprecationWarning
/Users/akashvelu/Documents/Research/Research_MobileSensing/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.
  PendingDeprecationWarning
/Users/akashvelu/Documents/Research/Research_MobileSensing/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.
  PendingDeprecationWarning
/Users/akashvelu/Documents/Research/Research_MobileSensing/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.
  PendingDeprecationWarning


In [4]:
#     sim_params = flow_params['sim']
#     env_params = flow_params['env']
#     net_params = flow_params['net']

#     # we want no autonomous vehicles in the simulation
#     vehicles = VehicleParams()
#     vehicles.add(veh_id='human',
#                  car_following_params=SumoCarFollowingParams(
#                      speed_mode=9,
#                  ),
#                  routing_controller=(ContinuousRouter, {}),
#                  lane_change_params=SumoLaneChangeParams(
#                      lane_change_mode=0,
#                  ),
#                  num_vehicles=1 * SCALING)

#     # only include human vehicles in inflows
#     flow_rate = 2300 * SCALING
#     inflow = InFlows()
#     inflow.add(veh_type='human', edge='1',
#                vehs_per_hour=flow_rate,
#                departLane='random', departSpeed=10)
#     net_params.inflows = inflow

#     # modify the rendering to match what is requested
#     # sim_params.render = render

#     # set the evaluation flag to True
#     env_params.evaluate = True

#     flow_params['env'].horizon = env_params.horizon

In [5]:
create_env, _ = make_create_env(flow_params)

In [6]:
env = create_env()

In [7]:
state = env.reset()
state

/Users/akashvelu/opt/anaconda3/envs/flow/lib/python3.6/subprocess.py:786: ResourceWarning: subprocess 28341 is still running
  ResourceWarning, source=self)


array([0.        , 0.1       , 0.05      , 0.        , 0.        ,
       0.        , 0.05      , 0.05      , 0.        , 0.05      ,
       0.        , 0.05      , 0.05      , 0.        , 0.1       ,
       0.        , 0.05      , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05      , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05      ,
       0.        , 0.05      , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.3234498 , 0.35290716, 0.        , 0.     

In [8]:
flow_params["exp_tag"]

'bottleneck_0'

In [ ]:
rl_actions = {}
for veh_id in env.k.vehicle.get_ids():
    print(veh_id)
    rl_actions[veh_id] = env.k.vehicle.get_acc_controller(veh_id).get_action(env)
print(flow_params.env['horizon'])

In [ ]:
state, reward, done, _ = env.step(env.action_space.sample())

In [ ]:
env.action_space.shape

In [ ]:
from env_params_test import name

In [ ]:
name

In [5]:
from env_params_test import flow_params

In [6]:
create_env, _ = make_create_env(flow_params)

In [7]:
env = create_env()

In [8]:
state = env.reset()
state


-----------------------
ring length: 265
v_max: 5.37714246265477
-----------------------


array([ 0.31246011, -0.00413767,  0.04496073])

In [12]:
vehicle_id = 'rl_0'

In [13]:
from flow.controllers.car_following_models import IDMController
car_following_params = SumoCarFollowingParams()
idm_controller = IDMController(vehicle_id, car_following_params=car_following_params)

In [15]:
env.step(idm_controller.get_action(env))

(array([ 0.31200989, -0.00526746,  0.04493147]), 0.6436939709782903, False, {})

In [ ]:
rl_actions

In [ ]:
env.step(rl_actions)

In [ ]:
for i in range(200):
    rl_actions = {}
    for veh_id in env.k.vehicle.get_ids():
        # print(veh_id)
        rl_actions[veh_id] = env.k.vehicle.get_acc_controller(veh_id).get_action(env)
        print(env.get_state())
    env.step(rl_actions)

In [ ]:
from flow.controllers.car_following_models import IDMController


In [ ]:
vehicle_id = env.k.vehicle.get_ids()[0]
vehicle_id

In [ ]:
car_following_params = SumoCarFollowingParams()
idm_controller = IDMController(vehicle_id, car_following_params=car_following_params)

In [ ]:
idm_controller.get_action(env)

In [ ]:
ob, rew, done, _ = env.step(rl_actions)

In [ ]:
from env_params import flow_params
create_env, _ = make_create_env(flow_params)
env = create_env()

In [ ]:
env.k.vehicle.get_ids()